name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/PrinceMerluza/devcenter-content-linter/releases/latest/download/content_linter
