name: blueprint-linter
on: [push]
jobs:
  evaluate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Linter
        run: |
          wget https://github.com/PrinceMerluza/devcenter-content-linter/releases/latest/download/content-linter.zip
          unzip content-linter.zip
          chmod +x ./bin/content_linter
      - name: Evaluate Content
        run: ./bin/content_linter ${{ github.workspace }} ./rules/blueprint.rule.json
