name: learn-github-actions
on: [push]
jobs:
  evaluate-content:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/PrinceMerluza/devcenter-content-linter/releases/latest/download/content-linter.zip
      - run: unzip content-linter.zip
      - run: chmod +x ./content_linter
      - uses: actions/checkout@v3
      - run: ./content_linter ${{ github.workspace }} ./rules/blueprint.rule.json
